// <auto-generated />
using System;
using Ajit_Bakery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ajit_Bakery.Migrations
{
    [DbContext(typeof(DataDBContext))]
    partial class DataDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ajit_Bakery.Models.BoxMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoxArea")
                        .HasColumnType("text");

                    b.Property<double>("BoxBreadth")
                        .HasColumnType("double precision");

                    b.Property<double>("BoxHeight")
                        .HasColumnType("double precision");

                    b.Property<double>("BoxLength")
                        .HasColumnType("double precision");

                    b.Property<string>("BoxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoxUom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Createtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Modifiedtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BoxMaster");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.DialMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Createtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DialArea")
                        .HasColumnType("text");

                    b.Property<double>("DialBreadth")
                        .HasColumnType("double precision");

                    b.Property<string>("DialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DialDiameter")
                        .HasColumnType("double precision");

                    b.Property<double>("DialLength")
                        .HasColumnType("double precision");

                    b.Property<string>("DialShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DialUom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DialWg")
                        .HasColumnType("double precision");

                    b.Property<string>("DialWgUom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Modifiedtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DialMaster");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.OutletMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Createtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Modifiedtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OutletAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutletCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutletContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutletContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutletName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutletMaster");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.ProductMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Createtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DialCode1")
                        .HasColumnType("text");

                    b.Property<string>("DialCode2")
                        .HasColumnType("text");

                    b.Property<double>("MRP")
                        .HasColumnType("double precision");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Modifiedtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PerGmRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Unitqty")
                        .HasColumnType("integer");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductMaster");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.TransportMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Createtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DriverContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Modifiedtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.Property<string>("VehicleCapacity")
                        .HasColumnType("text");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleNoOfTyre")
                        .HasColumnType("text");

                    b.Property<string>("VehicleOwn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleVolume")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TransportMaster");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.UserMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Createtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Modifiedtime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserDept")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserDesignation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
