// <auto-generated />
using Ajit_Bakery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ajit_Bakery.Migrations
{
    [DbContext(typeof(DataDBContext))]
    partial class DataDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Ajit_Bakery.Models.BoxMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BoxArea")
                        .HasColumnType("text");

                    b.Property<double>("BoxBreadth")
                        .HasColumnType("double precision");

                    b.Property<double>("BoxHeight")
                        .HasColumnType("double precision");

                    b.Property<double>("BoxLength")
                        .HasColumnType("double precision");

                    b.Property<string>("BoxNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BoxUom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreateDate")
                        .HasColumnType("text");

                    b.Property<string>("Createtime")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<string>("Modifiedtime")
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("BoxMaster");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.DialMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateDate")
                        .HasColumnType("text");

                    b.Property<string>("Createtime")
                        .HasColumnType("text");

                    b.Property<string>("DialArea")
                        .HasColumnType("text");

                    b.Property<double>("DialBreadth")
                        .HasColumnType("double precision");

                    b.Property<string>("DialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DialDiameter")
                        .HasColumnType("double precision");

                    b.Property<double>("DialLength")
                        .HasColumnType("double precision");

                    b.Property<string>("DialShape")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DialWg")
                        .HasColumnType("double precision");

                    b.Property<string>("DialWgUom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LengthUom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<string>("Modifiedtime")
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DialMaster");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.MenuModel", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Controller")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentMenuId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("icon")
                        .HasColumnType("text");

                    b.HasKey("MenuId");

                    b.ToTable("MenuModel");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.OutletMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateDate")
                        .HasColumnType("text");

                    b.Property<string>("Createtime")
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<string>("Modifiedtime")
                        .HasColumnType("text");

                    b.Property<string>("OutletAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutletCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutletContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutletContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OutletName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("OutletMaster");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.ProductMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreateDate")
                        .HasColumnType("text");

                    b.Property<string>("Createtime")
                        .HasColumnType("text");

                    b.Property<string>("Dial")
                        .HasColumnType("text");

                    b.Property<double>("MRP")
                        .HasColumnType("double precision");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<string>("Modifiedtime")
                        .HasColumnType("text");

                    b.Property<string>("PerGmRate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Unitqty")
                        .HasColumnType("integer");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductMaster");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.ProductionCapture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OutletName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Production_Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Production_Id")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Production_Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalQty")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProductionCapture");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.ProductionIds", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("ProductionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("ProductionIds");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.SaveProduction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DialCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("DialTierWg")
                        .HasColumnType("double precision");

                    b.Property<string>("DialTierWg_Uom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ProductGrossWg")
                        .HasColumnType("double precision");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<string>("SaveProduction_Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaveProduction_Time")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalNetWg")
                        .HasColumnType("double precision");

                    b.Property<string>("TotalNetWg_Uom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SaveProduction");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.TransportMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateDate")
                        .HasColumnType("text");

                    b.Property<string>("Createtime")
                        .HasColumnType("text");

                    b.Property<string>("DriverContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DriverName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<string>("Modifiedtime")
                        .HasColumnType("text");

                    b.Property<string>("User")
                        .HasColumnType("text");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleOwn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TransportMaster");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.UserManagment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserManagment");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.UserMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreateDate")
                        .HasColumnType("text");

                    b.Property<string>("Createtime")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("KeepLoogedIn")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedDate")
                        .HasColumnType("text");

                    b.Property<string>("Modifiedtime")
                        .HasColumnType("text");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserContactNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserDept")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserPassward")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserMaster");
                });

            modelBuilder.Entity("Ajit_Bakery.Models.UserType", b =>
                {
                    b.Property<int>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("user_id"));

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("usertype_name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.ToTable("UserType");
                });
#pragma warning restore 612, 618
        }
    }
}
